version: "3.8"

services:
  frontend-app:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-app
    command: wait-for backend-app:8081 -t 40 -- /usr/local/bin/start.sh
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/home/node/app
    depends_on:
      - backend-app
    networks:
      - network-app

  backend-app:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    container_name: backend-app
    restart: unless-stopped
    command: wait-for database:3306 -t 40 -- /usr/local/bin/start.sh
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/home/php/backend
    depends_on:
      - database
    networks:
      - network-app

  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=mypasswordroot
      # Set the database user and password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./_dbData:/var/lib/mysql
    networks:
      - network-app

networks:
  network-app:
    driver: bridge